// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    dailyLogs,
    avoidances,
    avoidanceChecks,
    appSettings,
    visits,
  ];
  late final Shape0 dailyLogs = Shape0(
    source: i0.VersionedTable(
      entityName: 'daily_logs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(day)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 avoidances = Shape1(
    source: i0.VersionedTable(
      entityName: 'avoidances',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_9, _column_10, _column_11, _column_12],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 avoidanceChecks = Shape2(
    source: i0.VersionedTable(
      entityName: 'avoidance_checks',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(day, avoidance_id)'],
      columns: [_column_0, _column_13],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 appSettings = Shape3(
    source: i0.VersionedTable(
      entityName: 'app_settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_14, _column_15],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 visits = Shape4(
    source: i0.VersionedTable(
      entityName: 'visits',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_9, _column_0, _column_16, _column_17, _column_8],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get day =>
      columnsByName['day']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get overall =>
      columnsByName['overall']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get pain =>
      columnsByName['pain']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get fatigue =>
      columnsByName['fatigue']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get sleep =>
      columnsByName['sleep']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get appetite =>
      columnsByName['appetite']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get mood =>
      columnsByName['mood']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get memo =>
      columnsByName['memo']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_0(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'day',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL CHECK (day GLOB \'[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]\')',
    );
i1.GeneratedColumn<int> _column_1(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'overall',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL CHECK (overall BETWEEN 1 AND 5)',
    );
i1.GeneratedColumn<int> _column_2(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'pain',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL CHECK (pain BETWEEN 1 AND 5)',
    );
i1.GeneratedColumn<int> _column_3(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'fatigue',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL CHECK (fatigue BETWEEN 1 AND 5)',
    );
i1.GeneratedColumn<int> _column_4(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'sleep',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL CHECK (sleep BETWEEN 1 AND 5)',
    );
i1.GeneratedColumn<int> _column_5(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'appetite',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL CHECK (appetite BETWEEN 1 AND 5)',
    );
i1.GeneratedColumn<int> _column_6(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'mood',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL CHECK (mood BETWEEN 1 AND 5)',
    );
i1.GeneratedColumn<String> _column_7(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'memo',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_8(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'updated_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get sortOrder =>
      columnsByName['sort_order']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get inUse =>
      columnsByName['in_use']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_9(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      hasAutoIncrement: true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL PRIMARY KEY AUTOINCREMENT',
    );
i1.GeneratedColumn<String> _column_10(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_11(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'sort_order',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_12(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'in_use',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 1 CHECK (in_use IN (0, 1))',
      defaultValue: const i1.CustomExpression('1'),
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get day =>
      columnsByName['day']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get avoidanceId =>
      columnsByName['avoidance_id']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_13(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'avoidance_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES avoidances(id)',
    );

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get key =>
      columnsByName['key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get value =>
      columnsByName['value']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_14(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'key',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_15(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'value',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get day =>
      columnsByName['day']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get toAsk =>
      columnsByName['to_ask']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get heard =>
      columnsByName['heard']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_16(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'to_ask',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_17(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'heard',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

final class Schema3 extends i0.VersionedSchema {
  Schema3({required super.database}) : super(version: 3);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    dailyLogs,
    avoidances,
    avoidanceChecks,
    appSettings,
    careProviders,
    visits,
  ];
  late final Shape0 dailyLogs = Shape0(
    source: i0.VersionedTable(
      entityName: 'daily_logs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(day)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 avoidances = Shape1(
    source: i0.VersionedTable(
      entityName: 'avoidances',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_9, _column_10, _column_11, _column_12],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 avoidanceChecks = Shape2(
    source: i0.VersionedTable(
      entityName: 'avoidance_checks',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(day, avoidance_id)'],
      columns: [_column_0, _column_13],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 appSettings = Shape3(
    source: i0.VersionedTable(
      entityName: 'app_settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_14, _column_15],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 careProviders = Shape5(
    source: i0.VersionedTable(
      entityName: 'care_providers',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'CHECK(hospital IS NOT NULL OR department IS NOT NULL OR doctor IS NOT NULL)',
      ],
      columns: [
        _column_9,
        _column_18,
        _column_19,
        _column_20,
        _column_12,
        _column_8,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 visits = Shape6(
    source: i0.VersionedTable(
      entityName: 'visits',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_9,
        _column_0,
        _column_16,
        _column_17,
        _column_8,
        _column_21,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get hospital =>
      columnsByName['hospital']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get department =>
      columnsByName['department']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get doctor =>
      columnsByName['doctor']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get inUse =>
      columnsByName['in_use']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_18(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'hospital',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NULL CHECK (hospital IS NULL OR NOT(TRIM(hospital) = \'\'))',
    );
i1.GeneratedColumn<String> _column_19(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'department',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NULL CHECK (department IS NULL OR NOT(TRIM(department) = \'\'))',
    );
i1.GeneratedColumn<String> _column_20(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'doctor',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NULL CHECK (doctor IS NULL OR NOT(TRIM(doctor) = \'\'))',
    );

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get day =>
      columnsByName['day']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get toAsk =>
      columnsByName['to_ask']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get heard =>
      columnsByName['heard']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get careProviderId =>
      columnsByName['care_provider_id']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_21(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'care_provider_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL REFERENCES care_providers(id)',
    );

final class Schema4 extends i0.VersionedSchema {
  Schema4({required super.database}) : super(version: 4);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    dailyLogs,
    precautions,
    precautionMarks,
    appSettings,
    careProviders,
    visits,
  ];
  late final Shape0 dailyLogs = Shape0(
    source: i0.VersionedTable(
      entityName: 'daily_logs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(day)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 precautions = Shape7(
    source: i0.VersionedTable(
      entityName: 'precautions',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(name, manner)'],
      columns: [_column_9, _column_22, _column_23, _column_11, _column_12],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 precautionMarks = Shape8(
    source: i0.VersionedTable(
      entityName: 'precaution_marks',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(day, precaution_id)'],
      columns: [_column_0, _column_24],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 appSettings = Shape3(
    source: i0.VersionedTable(
      entityName: 'app_settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_14, _column_15],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 careProviders = Shape5(
    source: i0.VersionedTable(
      entityName: 'care_providers',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'CHECK(hospital IS NOT NULL OR department IS NOT NULL OR doctor IS NOT NULL)',
      ],
      columns: [
        _column_9,
        _column_18,
        _column_19,
        _column_20,
        _column_12,
        _column_8,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 visits = Shape6(
    source: i0.VersionedTable(
      entityName: 'visits',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_9,
        _column_0,
        _column_16,
        _column_17,
        _column_8,
        _column_21,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get manner =>
      columnsByName['manner']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get sortOrder =>
      columnsByName['sort_order']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get inUse =>
      columnsByName['in_use']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_22(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL CHECK (NOT(TRIM(name) = \'\'))',
    );
i1.GeneratedColumn<String> _column_23(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'manner',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NOT NULL CHECK (manner IN (\'refrain\', \'keepUp\'))',
    );

class Shape8 extends i0.VersionedTable {
  Shape8({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get day =>
      columnsByName['day']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get precautionId =>
      columnsByName['precaution_id']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_24(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'precaution_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES precautions(id)',
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      case 2:
        final schema = Schema3(database: database);
        final migrator = i1.Migrator(database, schema);
        await from2To3(migrator, schema);
        return 3;
      case 3:
        final schema = Schema4(database: database);
        final migrator = i1.Migrator(database, schema);
        await from3To4(migrator, schema);
        return 4;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(
    from1To2: from1To2,
    from2To3: from2To3,
    from3To4: from3To4,
  ),
);
